# Generated by Django 4.2.3 on 2023-07-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256)),
                ('is_done', models.BooleanField(default=False)),
                ('complete_date', models.DateTimeField()),
                ('is_expired', models.BooleanField(default=False)),
            ],
        ),
    ]
