# Generated by Django 4.2.3 on 2023-07-18 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_rename_user_todo_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='user_id',
            new_name='user',
        ),
    ]
